nyc_taxi_lab:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'NYC_TAXI_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'NYC_TAXI_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'NYC_TAXI_WH') }}"
      schema: SILVER
      threads: 4
      client_session_keep_alive: false
      query_tag: lab_semana07_nyc_taxi_dbt

