-- Ejecuta este archivo una sola vez en Snowsight con ACCOUNTADMIN.
-- Cambia TU_USUARIO_SNOWFLAKE antes de ejecutar el GRANT final.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS NYC_TAXI_ROLE;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.GOLD;

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE NYC_TAXI_ROLE;
GRANT USAGE ON DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT CREATE SCHEMA ON DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI_DB.BRONZE TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI_DB.SILVER TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NYC_TAXI_DB.GOLD TO ROLE NYC_TAXI_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE NYC_TAXI_DB TO ROLE NYC_TAXI_ROLE;

-- Reemplaza el identificador por el mismo usuario configurado en .env.
GRANT ROLE NYC_TAXI_ROLE TO USER TU_USUARIO_SNOWFLAKE;

SHOW SCHEMAS IN DATABASE NYC_TAXI_DB;
SHOW GRANTS TO ROLE NYC_TAXI_ROLE;

