USE ROLE NYC_TAXI_ROLE;
USE WAREHOUSE NYC_TAXI_WH;
USE DATABASE NYC_TAXI_DB;

-- 1. Deben aparecer 20 meses exitosos y el catálogo de zonas.
SELECT DATASET, COUNT(*) AS SUCCESSFUL_LOADS, SUM(ROW_COUNT) AS ROWS_LOADED
FROM BRONZE.INGESTION_AUDIT
WHERE STATUS = 'SUCCESS'
GROUP BY DATASET
ORDER BY DATASET;

SELECT *
FROM BRONZE.INGESTION_AUDIT
ORDER BY DATASET, SOURCE_PERIOD;

-- 2. Volumen por capa.
SELECT 'BRONZE.YELLOW_TAXI_RAW' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT
FROM BRONZE.YELLOW_TAXI_RAW
UNION ALL
SELECT 'SILVER.TRIPS_CLEAN', COUNT(*) FROM SILVER.TRIPS_CLEAN
UNION ALL
SELECT 'GOLD.FCT_TRIPS', COUNT(*) FROM GOLD.FCT_TRIPS;

-- 3. Calidad mensual y justificación observable.
SELECT *
FROM SILVER.DQ_TRIPS_SUMMARY
ORDER BY SOURCE_PERIOD;

-- 4. Unicidad del grano; debe devolver cero filas.
SELECT TRIP_SK, COUNT(*) AS DUPLICATE_COUNT
FROM GOLD.FCT_TRIPS
GROUP BY TRIP_SK
HAVING COUNT(*) > 1;

-- 5. Integridad referencial manual; todos los conteos deben ser cero.
SELECT 'pickup_date' AS RELATIONSHIP, COUNT(*) AS ORPHANS
FROM GOLD.FCT_TRIPS F
LEFT JOIN GOLD.DIM_DATE D ON F.PICKUP_DATE_KEY = D.DATE_KEY
WHERE D.DATE_KEY IS NULL
UNION ALL
SELECT 'dropoff_date', COUNT(*)
FROM GOLD.FCT_TRIPS F
LEFT JOIN GOLD.DIM_DATE D ON F.DROPOFF_DATE_KEY = D.DATE_KEY
WHERE D.DATE_KEY IS NULL
UNION ALL
SELECT 'pickup_location', COUNT(*)
FROM GOLD.FCT_TRIPS F
LEFT JOIN GOLD.DIM_LOCATION D ON F.PICKUP_LOCATION_KEY = D.LOCATION_KEY
WHERE D.LOCATION_KEY IS NULL
UNION ALL
SELECT 'dropoff_location', COUNT(*)
FROM GOLD.FCT_TRIPS F
LEFT JOIN GOLD.DIM_LOCATION D ON F.DROPOFF_LOCATION_KEY = D.LOCATION_KEY
WHERE D.LOCATION_KEY IS NULL;

-- 6. Resultado analítico listo para consumir.
SELECT *
FROM GOLD.AGG_MONTHLY_KPIS
ORDER BY SOURCE_PERIOD;

